//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXNorthwindApp.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NorthwindEntitiesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NorthwindEntitiesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DXNorthwindApp.Localization.NorthwindEntitiesResources", typeof(NorthwindEntitiesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical list of product.
        /// </summary>
        public static string Alphabetical_list_of_product {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID.
        /// </summary>
        public static string Alphabetical_list_of_product_CategoryID {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_product_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Alphabetical_list_of_product_CategoryName {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_product_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string Alphabetical_list_of_product_Discontinued {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_product_Discontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        public static string Alphabetical_list_of_product_ProductID {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_product_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Alphabetical_list_of_product_ProductName {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_product_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Per Unit.
        /// </summary>
        public static string Alphabetical_list_of_product_QuantityPerUnit {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_product_QuantityPerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        public static string Alphabetical_list_of_product_ReorderLevel {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_product_ReorderLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID.
        /// </summary>
        public static string Alphabetical_list_of_product_SupplierID {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_product_SupplierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Alphabetical_list_of_product_UnitPrice {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_product_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units In Stock.
        /// </summary>
        public static string Alphabetical_list_of_product_UnitsInStock {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_product_UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units On Order.
        /// </summary>
        public static string Alphabetical_list_of_product_UnitsOnOrder {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_product_UnitsOnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical list of products.
        /// </summary>
        public static string Alphabetical_list_of_productPlural {
            get {
                return ResourceManager.GetString("Alphabetical_list_of_productPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID.
        /// </summary>
        public static string Category_CategoryID {
            get {
                return ResourceManager.GetString("Category_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Category_CategoryName {
            get {
                return ResourceManager.GetString("Category_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Category_Description {
            get {
                return ResourceManager.GetString("Category_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Category_Picture {
            get {
                return ResourceManager.GetString("Category_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Sales for 1997.
        /// </summary>
        public static string Category_Sales_for_1997 {
            get {
                return ResourceManager.GetString("Category_Sales_for_1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Category_Sales_for_1997_CategoryName {
            get {
                return ResourceManager.GetString("Category_Sales_for_1997_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Sales.
        /// </summary>
        public static string Category_Sales_for_1997_CategorySales {
            get {
                return ResourceManager.GetString("Category_Sales_for_1997_CategorySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Sales for 1997.
        /// </summary>
        public static string Category_Sales_for_1997Plural {
            get {
                return ResourceManager.GetString("Category_Sales_for_1997Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoryPlural {
            get {
                return ResourceManager.GetString("CategoryPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Product List.
        /// </summary>
        public static string Current_Product_List {
            get {
                return ResourceManager.GetString("Current_Product_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        public static string Current_Product_List_ProductID {
            get {
                return ResourceManager.GetString("Current_Product_List_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Current_Product_List_ProductName {
            get {
                return ResourceManager.GetString("Current_Product_List_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Product Lists.
        /// </summary>
        public static string Current_Product_ListPlural {
            get {
                return ResourceManager.GetString("Current_Product_ListPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Customer_Address {
            get {
                return ResourceManager.GetString("Customer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer and Suppliers by City.
        /// </summary>
        public static string Customer_and_Suppliers_by_City {
            get {
                return ResourceManager.GetString("Customer_and_Suppliers_by_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Customer_and_Suppliers_by_City_City {
            get {
                return ResourceManager.GetString("Customer_and_Suppliers_by_City_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Customer_and_Suppliers_by_City_CompanyName {
            get {
                return ResourceManager.GetString("Customer_and_Suppliers_by_City_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Customer_and_Suppliers_by_City_ContactName {
            get {
                return ResourceManager.GetString("Customer_and_Suppliers_by_City_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Customer_and_Suppliers_by_City_Relationship {
            get {
                return ResourceManager.GetString("Customer_and_Suppliers_by_City_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer and Suppliers by Cities.
        /// </summary>
        public static string Customer_and_Suppliers_by_CityPlural {
            get {
                return ResourceManager.GetString("Customer_and_Suppliers_by_CityPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Customer_City {
            get {
                return ResourceManager.GetString("Customer_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Customer_CompanyName {
            get {
                return ResourceManager.GetString("Customer_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Customer_ContactName {
            get {
                return ResourceManager.GetString("Customer_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string Customer_ContactTitle {
            get {
                return ResourceManager.GetString("Customer_ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Customer_Country {
            get {
                return ResourceManager.GetString("Customer_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string Customer_CustomerID {
            get {
                return ResourceManager.GetString("Customer_CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Customer_Fax {
            get {
                return ResourceManager.GetString("Customer_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Customer_Phone {
            get {
                return ResourceManager.GetString("Customer_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Customer_PostalCode {
            get {
                return ResourceManager.GetString("Customer_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Customer_Region {
            get {
                return ResourceManager.GetString("Customer_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Demographic.
        /// </summary>
        public static string CustomerDemographic {
            get {
                return ResourceManager.GetString("CustomerDemographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Desc.
        /// </summary>
        public static string CustomerDemographic_CustomerDesc {
            get {
                return ResourceManager.GetString("CustomerDemographic_CustomerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type ID.
        /// </summary>
        public static string CustomerDemographic_CustomerTypeID {
            get {
                return ResourceManager.GetString("CustomerDemographic_CustomerTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Demographics.
        /// </summary>
        public static string CustomerDemographicPlural {
            get {
                return ResourceManager.GetString("CustomerDemographicPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string CustomerPlural {
            get {
                return ResourceManager.GetString("CustomerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Employee_Address {
            get {
                return ResourceManager.GetString("Employee_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string Employee_BirthDate {
            get {
                return ResourceManager.GetString("Employee_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Employee_City {
            get {
                return ResourceManager.GetString("Employee_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Employee_Country {
            get {
                return ResourceManager.GetString("Employee_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee1.
        /// </summary>
        public static string Employee_Employee1 {
            get {
                return ResourceManager.GetString("Employee_Employee1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string Employee_EmployeeID {
            get {
                return ResourceManager.GetString("Employee_EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string Employee_Extension {
            get {
                return ResourceManager.GetString("Employee_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Employee_FirstName {
            get {
                return ResourceManager.GetString("Employee_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        public static string Employee_HireDate {
            get {
                return ResourceManager.GetString("Employee_HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string Employee_HomePhone {
            get {
                return ResourceManager.GetString("Employee_HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Employee_LastName {
            get {
                return ResourceManager.GetString("Employee_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Employee_Notes {
            get {
                return ResourceManager.GetString("Employee_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Employee_Photo {
            get {
                return ResourceManager.GetString("Employee_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Path.
        /// </summary>
        public static string Employee_PhotoPath {
            get {
                return ResourceManager.GetString("Employee_PhotoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Employee_PostalCode {
            get {
                return ResourceManager.GetString("Employee_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Employee_Region {
            get {
                return ResourceManager.GetString("Employee_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Employee_Title {
            get {
                return ResourceManager.GetString("Employee_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Of Courtesy.
        /// </summary>
        public static string Employee_TitleOfCourtesy {
            get {
                return ResourceManager.GetString("Employee_TitleOfCourtesy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string EmployeePlural {
            get {
                return ResourceManager.GetString("EmployeePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Invoice_Address {
            get {
                return ResourceManager.GetString("Invoice_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Invoice_City {
            get {
                return ResourceManager.GetString("Invoice_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Invoice_Country {
            get {
                return ResourceManager.GetString("Invoice_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string Invoice_CustomerID {
            get {
                return ResourceManager.GetString("Invoice_CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string Invoice_CustomerName {
            get {
                return ResourceManager.GetString("Invoice_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Invoice_Discount {
            get {
                return ResourceManager.GetString("Invoice_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Price.
        /// </summary>
        public static string Invoice_ExtendedPrice {
            get {
                return ResourceManager.GetString("Invoice_ExtendedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        public static string Invoice_Freight {
            get {
                return ResourceManager.GetString("Invoice_Freight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string Invoice_OrderDate {
            get {
                return ResourceManager.GetString("Invoice_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Invoice_OrderID {
            get {
                return ResourceManager.GetString("Invoice_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Invoice_PostalCode {
            get {
                return ResourceManager.GetString("Invoice_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        public static string Invoice_ProductID {
            get {
                return ResourceManager.GetString("Invoice_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Invoice_ProductName {
            get {
                return ResourceManager.GetString("Invoice_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Invoice_Quantity {
            get {
                return ResourceManager.GetString("Invoice_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Invoice_Region {
            get {
                return ResourceManager.GetString("Invoice_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Date.
        /// </summary>
        public static string Invoice_RequiredDate {
            get {
                return ResourceManager.GetString("Invoice_RequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesperson.
        /// </summary>
        public static string Invoice_Salesperson {
            get {
                return ResourceManager.GetString("Invoice_Salesperson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Address.
        /// </summary>
        public static string Invoice_ShipAddress {
            get {
                return ResourceManager.GetString("Invoice_ShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship City.
        /// </summary>
        public static string Invoice_ShipCity {
            get {
                return ResourceManager.GetString("Invoice_ShipCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Country.
        /// </summary>
        public static string Invoice_ShipCountry {
            get {
                return ResourceManager.GetString("Invoice_ShipCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Name.
        /// </summary>
        public static string Invoice_ShipName {
            get {
                return ResourceManager.GetString("Invoice_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string Invoice_ShippedDate {
            get {
                return ResourceManager.GetString("Invoice_ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Name.
        /// </summary>
        public static string Invoice_ShipperName {
            get {
                return ResourceManager.GetString("Invoice_ShipperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Postal Code.
        /// </summary>
        public static string Invoice_ShipPostalCode {
            get {
                return ResourceManager.GetString("Invoice_ShipPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Region.
        /// </summary>
        public static string Invoice_ShipRegion {
            get {
                return ResourceManager.GetString("Invoice_ShipRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Invoice_UnitPrice {
            get {
                return ResourceManager.GetString("Invoice_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string InvoicePlural {
            get {
                return ResourceManager.GetString("InvoicePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Order_Customer {
            get {
                return ResourceManager.GetString("Order_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Detail.
        /// </summary>
        public static string Order_Detail {
            get {
                return ResourceManager.GetString("Order_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Order_Detail_Discount {
            get {
                return ResourceManager.GetString("Order_Detail_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order_Detail_Order {
            get {
                return ResourceManager.GetString("Order_Detail_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Order_Detail_Product {
            get {
                return ResourceManager.GetString("Order_Detail_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Order_Detail_Quantity {
            get {
                return ResourceManager.GetString("Order_Detail_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Order_Detail_UnitPrice {
            get {
                return ResourceManager.GetString("Order_Detail_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string Order_DetailPlural {
            get {
                return ResourceManager.GetString("Order_DetailPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details Extended.
        /// </summary>
        public static string Order_Details_Extended {
            get {
                return ResourceManager.GetString("Order_Details_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Order_Details_Extended_Discount {
            get {
                return ResourceManager.GetString("Order_Details_Extended_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Price.
        /// </summary>
        public static string Order_Details_Extended_ExtendedPrice {
            get {
                return ResourceManager.GetString("Order_Details_Extended_ExtendedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Order_Details_Extended_OrderID {
            get {
                return ResourceManager.GetString("Order_Details_Extended_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        public static string Order_Details_Extended_ProductID {
            get {
                return ResourceManager.GetString("Order_Details_Extended_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Order_Details_Extended_ProductName {
            get {
                return ResourceManager.GetString("Order_Details_Extended_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Order_Details_Extended_Quantity {
            get {
                return ResourceManager.GetString("Order_Details_Extended_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Order_Details_Extended_UnitPrice {
            get {
                return ResourceManager.GetString("Order_Details_Extended_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details Extendeds.
        /// </summary>
        public static string Order_Details_ExtendedPlural {
            get {
                return ResourceManager.GetString("Order_Details_ExtendedPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Order_Employee {
            get {
                return ResourceManager.GetString("Order_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        public static string Order_Freight {
            get {
                return ResourceManager.GetString("Order_Freight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string Order_OrderDate {
            get {
                return ResourceManager.GetString("Order_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Order_OrderID {
            get {
                return ResourceManager.GetString("Order_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Date.
        /// </summary>
        public static string Order_RequiredDate {
            get {
                return ResourceManager.GetString("Order_RequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Address.
        /// </summary>
        public static string Order_ShipAddress {
            get {
                return ResourceManager.GetString("Order_ShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship City.
        /// </summary>
        public static string Order_ShipCity {
            get {
                return ResourceManager.GetString("Order_ShipCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Country.
        /// </summary>
        public static string Order_ShipCountry {
            get {
                return ResourceManager.GetString("Order_ShipCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Name.
        /// </summary>
        public static string Order_ShipName {
            get {
                return ResourceManager.GetString("Order_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string Order_ShippedDate {
            get {
                return ResourceManager.GetString("Order_ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper.
        /// </summary>
        public static string Order_Shipper {
            get {
                return ResourceManager.GetString("Order_Shipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Postal Code.
        /// </summary>
        public static string Order_ShipPostalCode {
            get {
                return ResourceManager.GetString("Order_ShipPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Region.
        /// </summary>
        public static string Order_ShipRegion {
            get {
                return ResourceManager.GetString("Order_ShipRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Subtotal.
        /// </summary>
        public static string Order_Subtotal {
            get {
                return ResourceManager.GetString("Order_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Order_Subtotal_OrderID {
            get {
                return ResourceManager.GetString("Order_Subtotal_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Order_Subtotal_Subtotal {
            get {
                return ResourceManager.GetString("Order_Subtotal_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Subtotals.
        /// </summary>
        public static string Order_SubtotalPlural {
            get {
                return ResourceManager.GetString("Order_SubtotalPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string OrderPlural {
            get {
                return ResourceManager.GetString("OrderPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Qry.
        /// </summary>
        public static string Orders_Qry {
            get {
                return ResourceManager.GetString("Orders_Qry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Orders_Qry_Address {
            get {
                return ResourceManager.GetString("Orders_Qry_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Orders_Qry_City {
            get {
                return ResourceManager.GetString("Orders_Qry_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Orders_Qry_CompanyName {
            get {
                return ResourceManager.GetString("Orders_Qry_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Orders_Qry_Country {
            get {
                return ResourceManager.GetString("Orders_Qry_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string Orders_Qry_CustomerID {
            get {
                return ResourceManager.GetString("Orders_Qry_CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string Orders_Qry_EmployeeID {
            get {
                return ResourceManager.GetString("Orders_Qry_EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        public static string Orders_Qry_Freight {
            get {
                return ResourceManager.GetString("Orders_Qry_Freight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string Orders_Qry_OrderDate {
            get {
                return ResourceManager.GetString("Orders_Qry_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Orders_Qry_OrderID {
            get {
                return ResourceManager.GetString("Orders_Qry_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Orders_Qry_PostalCode {
            get {
                return ResourceManager.GetString("Orders_Qry_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Orders_Qry_Region {
            get {
                return ResourceManager.GetString("Orders_Qry_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Date.
        /// </summary>
        public static string Orders_Qry_RequiredDate {
            get {
                return ResourceManager.GetString("Orders_Qry_RequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Address.
        /// </summary>
        public static string Orders_Qry_ShipAddress {
            get {
                return ResourceManager.GetString("Orders_Qry_ShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship City.
        /// </summary>
        public static string Orders_Qry_ShipCity {
            get {
                return ResourceManager.GetString("Orders_Qry_ShipCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Country.
        /// </summary>
        public static string Orders_Qry_ShipCountry {
            get {
                return ResourceManager.GetString("Orders_Qry_ShipCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Name.
        /// </summary>
        public static string Orders_Qry_ShipName {
            get {
                return ResourceManager.GetString("Orders_Qry_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string Orders_Qry_ShippedDate {
            get {
                return ResourceManager.GetString("Orders_Qry_ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Postal Code.
        /// </summary>
        public static string Orders_Qry_ShipPostalCode {
            get {
                return ResourceManager.GetString("Orders_Qry_ShipPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Region.
        /// </summary>
        public static string Orders_Qry_ShipRegion {
            get {
                return ResourceManager.GetString("Orders_Qry_ShipRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Via.
        /// </summary>
        public static string Orders_Qry_ShipVia {
            get {
                return ResourceManager.GetString("Orders_Qry_ShipVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Qries.
        /// </summary>
        public static string Orders_QryPlural {
            get {
                return ResourceManager.GetString("Orders_QryPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Product_Category {
            get {
                return ResourceManager.GetString("Product_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string Product_Discontinued {
            get {
                return ResourceManager.GetString("Product_Discontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        public static string Product_ProductID {
            get {
                return ResourceManager.GetString("Product_ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Product_ProductName {
            get {
                return ResourceManager.GetString("Product_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Per Unit.
        /// </summary>
        public static string Product_QuantityPerUnit {
            get {
                return ResourceManager.GetString("Product_QuantityPerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        public static string Product_ReorderLevel {
            get {
                return ResourceManager.GetString("Product_ReorderLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sales for 1997.
        /// </summary>
        public static string Product_Sales_for_1997 {
            get {
                return ResourceManager.GetString("Product_Sales_for_1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Product_Sales_for_1997_CategoryName {
            get {
                return ResourceManager.GetString("Product_Sales_for_1997_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Product_Sales_for_1997_ProductName {
            get {
                return ResourceManager.GetString("Product_Sales_for_1997_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sales.
        /// </summary>
        public static string Product_Sales_for_1997_ProductSales {
            get {
                return ResourceManager.GetString("Product_Sales_for_1997_ProductSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sales for 1997.
        /// </summary>
        public static string Product_Sales_for_1997Plural {
            get {
                return ResourceManager.GetString("Product_Sales_for_1997Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Product_Supplier {
            get {
                return ResourceManager.GetString("Product_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Product_UnitPrice {
            get {
                return ResourceManager.GetString("Product_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units In Stock.
        /// </summary>
        public static string Product_UnitsInStock {
            get {
                return ResourceManager.GetString("Product_UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units On Order.
        /// </summary>
        public static string Product_UnitsOnOrder {
            get {
                return ResourceManager.GetString("Product_UnitsOnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ProductPlural {
            get {
                return ResourceManager.GetString("ProductPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Above Average Price.
        /// </summary>
        public static string Products_Above_Average_Price {
            get {
                return ResourceManager.GetString("Products_Above_Average_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Products_Above_Average_Price_ProductName {
            get {
                return ResourceManager.GetString("Products_Above_Average_Price_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Products_Above_Average_Price_UnitPrice {
            get {
                return ResourceManager.GetString("Products_Above_Average_Price_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Above Average Prices.
        /// </summary>
        public static string Products_Above_Average_PricePlural {
            get {
                return ResourceManager.GetString("Products_Above_Average_PricePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products by Category.
        /// </summary>
        public static string Products_by_Category {
            get {
                return ResourceManager.GetString("Products_by_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Products_by_Category_CategoryName {
            get {
                return ResourceManager.GetString("Products_by_Category_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinued.
        /// </summary>
        public static string Products_by_Category_Discontinued {
            get {
                return ResourceManager.GetString("Products_by_Category_Discontinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Products_by_Category_ProductName {
            get {
                return ResourceManager.GetString("Products_by_Category_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Per Unit.
        /// </summary>
        public static string Products_by_Category_QuantityPerUnit {
            get {
                return ResourceManager.GetString("Products_by_Category_QuantityPerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units In Stock.
        /// </summary>
        public static string Products_by_Category_UnitsInStock {
            get {
                return ResourceManager.GetString("Products_by_Category_UnitsInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products by Categories.
        /// </summary>
        public static string Products_by_CategoryPlural {
            get {
                return ResourceManager.GetString("Products_by_CategoryPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Description.
        /// </summary>
        public static string Region_RegionDescription {
            get {
                return ResourceManager.GetString("Region_RegionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region ID.
        /// </summary>
        public static string Region_RegionID {
            get {
                return ResourceManager.GetString("Region_RegionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string RegionPlural {
            get {
                return ResourceManager.GetString("RegionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by Category.
        /// </summary>
        public static string Sales_by_Category {
            get {
                return ResourceManager.GetString("Sales_by_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID.
        /// </summary>
        public static string Sales_by_Category_CategoryID {
            get {
                return ResourceManager.GetString("Sales_by_Category_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string Sales_by_Category_CategoryName {
            get {
                return ResourceManager.GetString("Sales_by_Category_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Sales_by_Category_ProductName {
            get {
                return ResourceManager.GetString("Sales_by_Category_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sales.
        /// </summary>
        public static string Sales_by_Category_ProductSales {
            get {
                return ResourceManager.GetString("Sales_by_Category_ProductSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales by Categories.
        /// </summary>
        public static string Sales_by_CategoryPlural {
            get {
                return ResourceManager.GetString("Sales_by_CategoryPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Totals by Amount.
        /// </summary>
        public static string Sales_Totals_by_Amount {
            get {
                return ResourceManager.GetString("Sales_Totals_by_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Sales_Totals_by_Amount_CompanyName {
            get {
                return ResourceManager.GetString("Sales_Totals_by_Amount_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Sales_Totals_by_Amount_OrderID {
            get {
                return ResourceManager.GetString("Sales_Totals_by_Amount_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Amount.
        /// </summary>
        public static string Sales_Totals_by_Amount_SaleAmount {
            get {
                return ResourceManager.GetString("Sales_Totals_by_Amount_SaleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string Sales_Totals_by_Amount_ShippedDate {
            get {
                return ResourceManager.GetString("Sales_Totals_by_Amount_ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Totals by Amounts.
        /// </summary>
        public static string Sales_Totals_by_AmountPlural {
            get {
                return ResourceManager.GetString("Sales_Totals_by_AmountPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper.
        /// </summary>
        public static string Shipper {
            get {
                return ResourceManager.GetString("Shipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Shipper_CompanyName {
            get {
                return ResourceManager.GetString("Shipper_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Shipper_Phone {
            get {
                return ResourceManager.GetString("Shipper_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper ID.
        /// </summary>
        public static string Shipper_ShipperID {
            get {
                return ResourceManager.GetString("Shipper_ShipperID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shippers.
        /// </summary>
        public static string ShipperPlural {
            get {
                return ResourceManager.GetString("ShipperPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of Sales by Quarter.
        /// </summary>
        public static string Summary_of_Sales_by_Quarter {
            get {
                return ResourceManager.GetString("Summary_of_Sales_by_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Summary_of_Sales_by_Quarter_OrderID {
            get {
                return ResourceManager.GetString("Summary_of_Sales_by_Quarter_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string Summary_of_Sales_by_Quarter_ShippedDate {
            get {
                return ResourceManager.GetString("Summary_of_Sales_by_Quarter_ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Summary_of_Sales_by_Quarter_Subtotal {
            get {
                return ResourceManager.GetString("Summary_of_Sales_by_Quarter_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of Sales by Quarters.
        /// </summary>
        public static string Summary_of_Sales_by_QuarterPlural {
            get {
                return ResourceManager.GetString("Summary_of_Sales_by_QuarterPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of Sales by Year.
        /// </summary>
        public static string Summary_of_Sales_by_Year {
            get {
                return ResourceManager.GetString("Summary_of_Sales_by_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Summary_of_Sales_by_Year_OrderID {
            get {
                return ResourceManager.GetString("Summary_of_Sales_by_Year_OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped Date.
        /// </summary>
        public static string Summary_of_Sales_by_Year_ShippedDate {
            get {
                return ResourceManager.GetString("Summary_of_Sales_by_Year_ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Summary_of_Sales_by_Year_Subtotal {
            get {
                return ResourceManager.GetString("Summary_of_Sales_by_Year_Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of Sales by Years.
        /// </summary>
        public static string Summary_of_Sales_by_YearPlural {
            get {
                return ResourceManager.GetString("Summary_of_Sales_by_YearPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Supplier_Address {
            get {
                return ResourceManager.GetString("Supplier_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Supplier_City {
            get {
                return ResourceManager.GetString("Supplier_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Supplier_CompanyName {
            get {
                return ResourceManager.GetString("Supplier_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string Supplier_ContactName {
            get {
                return ResourceManager.GetString("Supplier_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Title.
        /// </summary>
        public static string Supplier_ContactTitle {
            get {
                return ResourceManager.GetString("Supplier_ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Supplier_Country {
            get {
                return ResourceManager.GetString("Supplier_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Supplier_Fax {
            get {
                return ResourceManager.GetString("Supplier_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Supplier_HomePage {
            get {
                return ResourceManager.GetString("Supplier_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Supplier_Phone {
            get {
                return ResourceManager.GetString("Supplier_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Supplier_PostalCode {
            get {
                return ResourceManager.GetString("Supplier_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Supplier_Region {
            get {
                return ResourceManager.GetString("Supplier_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID.
        /// </summary>
        public static string Supplier_SupplierID {
            get {
                return ResourceManager.GetString("Supplier_SupplierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string SupplierPlural {
            get {
                return ResourceManager.GetString("SupplierPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory.
        /// </summary>
        public static string Territory {
            get {
                return ResourceManager.GetString("Territory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Territory_Region {
            get {
                return ResourceManager.GetString("Territory_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory Description.
        /// </summary>
        public static string Territory_TerritoryDescription {
            get {
                return ResourceManager.GetString("Territory_TerritoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territory ID.
        /// </summary>
        public static string Territory_TerritoryID {
            get {
                return ResourceManager.GetString("Territory_TerritoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Territories.
        /// </summary>
        public static string TerritoryPlural {
            get {
                return ResourceManager.GetString("TerritoryPlural", resourceCulture);
            }
        }
    }
}
